default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: mocky_mouse_development

test:
  <<: *default
  database: mocky_mouse_test

production:
  <<: *default
  database: mocky_mouse_production
  username: mocky_mouse
  password: <%= ENV["MOCKY_MOUSE_DATABASE_PASSWORD"] %>
